import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright';
import { AxeBuilder } from '@axe-core/playwright';
import { createApp } from '../apps/server/src/app.js';
import { loadConfig } from '../apps/server/src/config.js';
import { profiles } from '@blindspot/shared';

const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'blindspot-ui-data-'));
const app = await createApp({ ...loadConfig({}), dataDir });
const url = await app.listen({ host: '127.0.0.1', port: 0 });
const browser = await chromium.launch();
const errors: string[] = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', acceptDownloads: true });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.getByRole('heading', { name: 'See your website’s blind spots.' }).waitFor();
  await page.getByText('Audit options', { exact: true }).click();
  await page.getByRole('button', { name: 'Clear all', exact: true }).click();
  assert.equal(await page.getByRole('checkbox', { checked: true }).count(), 0);
  await page.getByRole('button', { name: 'Select all', exact: true }).click();
  assert.equal(await page.getByRole('checkbox', { checked: true }).count(), profiles.length);
  const homeAxe = await new AxeBuilder({ page }).analyze();
  const homeShot = path.join(os.tmpdir(), 'blindspot-home.png'); await page.screenshot({ path: homeShot, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile home overflow');
  const mobileShot = path.join(os.tmpdir(), 'blindspot-mobile.png'); await page.screenshot({ path: mobileShot, fullPage: true });
  await page.getByRole('button', { name: 'Explore a sample report' }).click();
  await page.getByRole('heading', { name: 'Accessibility report' }).waitFor({ timeout: 20_000 });
  assert.match(page.url(), /audit=/);
  await page.reload();
  await page.getByRole('heading', { name: 'Accessibility report' }).waitFor();
  const overflowing = await page.evaluate(() => [...document.querySelectorAll('*')].filter(el => el.getBoundingClientRect().right > innerWidth + 1).map(el => ({ tag: el.tagName, class: el.className, width: el.getBoundingClientRect().width })));
  assert.deepEqual(overflowing, [], 'Mobile report overflow');
  const reportMobile = path.join(os.tmpdir(), 'blindspot-report-mobile.png'); await page.screenshot({ path: reportMobile, fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: /Filters/ }).click();
  await page.getByRole('combobox', { name: /Severity/ }).selectOption('serious');
  const reportAxe = await new AxeBuilder({ page }).analyze();
  const reportShot = path.join(os.tmpdir(), 'blindspot-report.png'); await page.screenshot({ path: reportShot, fullPage: true });
  const downloaded = page.waitForEvent('download'); await page.getByRole('button', { name: 'JSON', exact: true }).click();
  assert.match((await downloaded).suggestedFilename(), /\.json$/);
  console.log(JSON.stringify({ url, homeAxe: homeAxe.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => ({ target: n.target, reason: n.failureSummary })) })), reportAxe: reportAxe.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => ({ target: n.target, reason: n.failureSummary })) })), errors, screenshots: [homeShot, mobileShot, reportShot, reportMobile] }, null, 2));
  assert.equal(homeAxe.violations.length, 0, 'Home accessibility violations');
  assert.equal(reportAxe.violations.length, 0, 'Report accessibility violations');
  assert.deepEqual(errors, []);
} finally { await browser.close(); await app.close(); await fs.rm(dataDir, { recursive: true, force: true }); }
