import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright';
import { AxeBuilder } from '@axe-core/playwright';
import { createApp } from '../apps/server/src/app.js';
import { loadConfig } from '../apps/server/src/config.js';

const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'blindspot-ui-data-'));
const app = await createApp({ ...loadConfig({}), dataDir });
const url = await app.listen({ host: '127.0.0.1', port: 0 });
const browser = await chromium.launch();
const errors: string[] = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', acceptDownloads: true });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.getByRole('heading', { name: 'See your website’s blind spots.' }).waitFor();
  const homeAxe = await new AxeBuilder({ page }).analyze();
  const homeShot = path.join(os.tmpdir(), 'blindspot-home.png'); await page.screenshot({ path: homeShot, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile home overflow');
  const mobileShot = path.join(os.tmpdir(), 'blindspot-mobile.png'); await page.screenshot({ path: mobileShot, fullPage: true });
  await page.getByRole('button', { name: 'Explore a sample report' }).click();
  await page.getByRole('heading', { name: 'Accessibility report' }).waitFor({ timeout: 20_000 });
  assert.match(page.url(), /audit=/);
  await page.reload();
  await page.getByRole('heading', { name: 'Accessibility report' }).waitFor();
  assert.equal(await page.locator('.report-secondary[open]').count(), 0);
  await page.locator('.issue-list-row').last().click();
  assert.equal(await page.locator('.issue-list-row[aria-pressed=true]').count(), 1);
  assert.equal(await page.locator('#selected-issue-title').innerText(), 'Text contrast is too low');
  await page.locator('.issue-list-row').first().click();
  const location = page.getByRole('region', { name: 'Issue location' });
  assert.equal(await location.locator('.finding-page-link').getAttribute('href'), 'https://sample.blindspot.example/sign-in');
  const screenshot = location.getByRole('img');
  await screenshot.scrollIntoViewIfNeeded();
  await screenshot.evaluate((img: HTMLImageElement) => img.decode());
  assert.ok(await screenshot.evaluate((img: HTMLImageElement) => img.naturalWidth > 0));
  const originalTitle = await page.locator('#selected-issue-title').innerText();
  await page.getByRole('button', { name: 'Mark as seen', exact: true }).click();
  assert.equal(await page.locator('.issue-list-row').last().getAttribute('data-review'), 'seen');
  assert.equal(await page.locator('#selected-issue-title').innerText(), originalTitle);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  assert.equal(await page.locator('.issue-list-row').first().getAttribute('data-review'), 'open');
  await page.getByRole('button', { name: 'Mark as resolved', exact: true }).click();
  assert.equal(await page.locator('.issue-list-row').last().getAttribute('data-review'), 'resolved');
  await page.reload();
  await page.getByRole('heading', { name: 'Accessibility report' }).waitFor();
  await page.locator('.issue-list-row').filter({ hasText: originalTitle }).click();
  assert.equal(await page.locator('.issue-list-row[aria-pressed=true]').getAttribute('data-review'), 'resolved');
  assert.equal(await page.locator('.review-scope').count(), 0);
  await page.getByRole('button', { name: 'Reopen', exact: true }).click();
  assert.equal(await page.locator('.issue-list-row').first().getAttribute('data-review'), 'open');
  await page.getByRole('button', { name: 'Mark as resolved', exact: true }).click();
  await screenshot.evaluate((img: HTMLImageElement) => img.decode());
  const overflowing = await page.evaluate(() => [...document.querySelectorAll('*')].filter(el => el.getBoundingClientRect().right > innerWidth + 1).map(el => ({ tag: el.tagName, class: el.className, width: el.getBoundingClientRect().width })));
  assert.deepEqual(overflowing, [], 'Mobile report overflow');
  const reportMobile = path.join(os.tmpdir(), 'blindspot-report-mobile.png'); await page.screenshot({ path: reportMobile, fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('combobox', { name: 'Profile', exact: true }).selectOption('blindness');
  assert.equal(await page.getByRole('combobox', { name: 'Profile', exact: true }).inputValue(), 'blindness');
  await page.getByRole('combobox', { name: 'Profile', exact: true }).selectOption('all');
  const reportAxe = await new AxeBuilder({ page }).analyze();
  const reportShot = path.join(os.tmpdir(), 'blindspot-report.png'); await page.screenshot({ path: reportShot, fullPage: true });
  await location.screenshot({ path: path.join(os.tmpdir(), 'blindspot-finding-location.png') });
  const downloaded = page.waitForEvent('download'); await page.getByRole('button', { name: 'JSON', exact: true }).click();
  const reportDownload = await downloaded;
  assert.match(reportDownload.suggestedFilename(), /\.json$/);
  const exported = JSON.parse(await fs.readFile((await reportDownload.path())!, 'utf8'));
  assert.ok(Object.values(exported.manualReview.marks).includes('resolved'));
  assert.ok(exported.report.findings.some((finding: { status: string }) => finding.status === 'fail'), 'Manual review must not rewrite audit failures');
  const technical = page.locator('.selected-issue .report-technical');
  await technical.getByText('Technical details', { exact: true }).click();
  assert.equal(await technical.locator('p').count(), 0, 'Technical details should not repeat report prose');
  assert.equal(await technical.getByRole('link', { name: 'Rendered HTML', exact: true }).count(), 1);
  const rawDownload = page.waitForEvent('download');
  await technical.getByRole('button', { name: 'Raw finding JSON' }).click();
  const rawFinding = JSON.parse(await fs.readFile((await (await rawDownload).path())!, 'utf8'));
  assert.ok(rawFinding.evidence.length > 0, 'Full evidence remains downloadable');
  await page.locator('.selected-issue').screenshot({ path: path.join(os.tmpdir(), 'blindspot-review-details.png') });
  // Exercise report category changes, including a genuinely empty selection.
  await page.getByRole('group', { name: 'Result categories' }).getByRole('button', { name: /Suggestions/ }).click();
  await page.getByRole('heading', { name: 'No finding to display' }).waitFor();
  await page.getByRole('group', { name: 'Result categories' }).getByRole('button', { name: /Confirmed/ }).click();
  const savedAudit = await (await page.request.get(`${url}/api/audits/${new URL(page.url()).searchParams.get('audit')}`)).json();
  let failTrace = true;
  await page.route('**/api/audits/*/events?after=0', route => route.fulfill({ status: failTrace ? 503 : 200, contentType: 'application/json', body: JSON.stringify(failTrace ? { error: 'Fixture unavailable' } : { events: [
    { id: 1, timestamp: savedAudit.createdAt, type: 'navigation', message: 'Opened sign-in page', pageStateId: savedAudit.pageStates[0].id },
    { id: 2, timestamp: savedAudit.updatedAt, type: 'warning', message: 'Fixture warning without a capture' },
  ] }) }));
  await page.getByText('Run trace · debug', { exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'Could not load the event log' }).waitFor();
  failTrace = false;
  await page.getByRole('button', { name: 'Retry', exact: true }).click();
  await page.getByRole('button', { name: /Opened sign-in page/ }).click();
  const traceDetails = page.getByRole('region', { name: 'Trace entry details' });
  await traceDetails.getByRole('img').evaluate((img: HTMLImageElement) => img.decode());
  assert.equal(await traceDetails.getByRole('link', { name: 'Rendered DOM', exact: true }).count(), 1);
  await page.getByRole('combobox', { name: 'Show', exact: true }).selectOption('warnings');
  await traceDetails.getByText('This event has no linked page capture.', { exact: false }).waitFor();
  assert.equal(await traceDetails.getByRole('img').count(), 0);
  await page.getByRole('combobox', { name: 'Show', exact: true }).selectOption('pages');
  const traceDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download trace', exact: true }).click();
  assert.match((await traceDownload).suggestedFilename(), /-trace\.json$/);
  const traceAxe = await new AxeBuilder({ page }).analyze();
  assert.equal(traceAxe.violations.length, 0, JSON.stringify(traceAxe.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.target) }))));
  await page.locator('.run-trace').screenshot({ path: path.join(os.tmpdir(), 'blindspot-trace.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile trace overflow');
  console.log(JSON.stringify({ url, homeAxe: homeAxe.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => ({ target: n.target, reason: n.failureSummary })) })), reportAxe: reportAxe.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => ({ target: n.target, reason: n.failureSummary })) })), errors, screenshots: [homeShot, mobileShot, reportShot, reportMobile] }, null, 2));
  assert.equal(homeAxe.violations.length, 0, 'Home accessibility violations');
  assert.equal(reportAxe.violations.length, 0, 'Report accessibility violations');
  assert.deepEqual(errors, []);
} finally { await browser.close(); await app.close(); await fs.rm(dataDir, { recursive: true, force: true }); }
